-- MySQL Script generated by MySQL Workbench
-- 01/25/17 23:46:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controleOS
-- -----------------------------------------------------
-- Banco de dados, responsável por persistir os dados do sistema de controle de O.S. da Tec Port Informática.

-- -----------------------------------------------------
-- Schema controleOS
--
-- Banco de dados, responsável por persistir os dados do sistema de controle de O.S. da Tec Port Informática.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controleOS` DEFAULT CHARACTER SET utf8 ;
USE `controleOS` ;

-- -----------------------------------------------------
-- Table `controleOS`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`usuarios` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `login_usuario` VARCHAR(30) NOT NULL,
  `senha_usuario` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`cidades` (
  `cod_cidade` INT NOT NULL AUTO_INCREMENT,
  `desc_cidade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`clientes` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `cod_pers_cliente` VARCHAR(10) NOT NULL,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `endereco_cliente` VARCHAR(100) NOT NULL,
  `bairro_cliente` VARCHAR(45) NOT NULL,
  `cod_cidade_cliente` INT NOT NULL,
  `telefone_um_cliente` VARCHAR(30) NOT NULL,
  `telefone_dois_cliente` VARCHAR(30) NOT NULL,
  `ip_cliente` VARCHAR(20) NULL,
  `pop_cliente` VARCHAR(100) NULL,
  `user_pppoe_cliente` VARCHAR(50) NULL,
  `pass_pppoe_cliente` VARCHAR(50) NULL,
  `plano_cliente` VARCHAR(10) NULL,
  PRIMARY KEY (`cod_cliente`, `cod_cidade_cliente`),
  INDEX `cod_cidade_idx` (`cod_cidade_cliente` ASC),
  CONSTRAINT `cod_cidade`
    FOREIGN KEY (`cod_cidade_cliente`)
    REFERENCES `controleOS`.`cidades` (`cod_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`atendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`atendentes` (
  `cod_atendente` INT NOT NULL AUTO_INCREMENT,
  `nome_atentente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_atendente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`tecnicos` (
  `cod_tecnico` INT NOT NULL AUTO_INCREMENT,
  `nome_tecnico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_tecnico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`tipos` (
  `cod_tipo` INT NOT NULL AUTO_INCREMENT,
  `desc_tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`ordens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`ordens` (
  `cod_ondem` INT NOT NULL AUTO_INCREMENT,
  `desc_ordem` VARCHAR(200) NOT NULL,
  `data_cad_ordem` DATE NOT NULL,
  `data_inicio_ordem` DATE NULL,
  `data_fim_ordem` DATE NULL,
  `hora_cad_ordem` TIME NOT NULL,
  `hora_inicio_ordem` TIME NULL,
  `hora_fim_ordem` TIME NULL,
  `cod_tipo_ordem` INT NOT NULL,
  `cod_cliente_ordem` INT NOT NULL,
  `cod_tecnico_ordem` INT NOT NULL,
  `cod_atendente_ordem` INT NOT NULL,
  `desc_total_ordem` TEXT NULL,
  `desc_resolve_ordem` TEXT NULL,
  `status_ordem` VARCHAR(20) NOT NULL,
  `solicita_ordem` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_ondem`, `cod_tipo_ordem`, `cod_cliente_ordem`, `cod_tecnico_ordem`, `cod_atendente_ordem`),
  INDEX `cod_cliente_idx` (`cod_cliente_ordem` ASC),
  INDEX `cod_tecnico_idx` (`cod_tecnico_ordem` ASC),
  INDEX `cod_atendente_idx` (`cod_atendente_ordem` ASC),
  INDEX `cod_tipo_idx` (`cod_tipo_ordem` ASC),
  CONSTRAINT `cod_cliente`
    FOREIGN KEY (`cod_cliente_ordem`)
    REFERENCES `controleOS`.`clientes` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_tecnico`
    FOREIGN KEY (`cod_tecnico_ordem`)
    REFERENCES `controleOS`.`tecnicos` (`cod_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_atendente`
    FOREIGN KEY (`cod_atendente_ordem`)
    REFERENCES `controleOS`.`atendentes` (`cod_atendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_tipo`
    FOREIGN KEY (`cod_tipo_ordem`)
    REFERENCES `controleOS`.`tipos` (`cod_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`logs` (
  `cod_log` INT NOT NULL AUTO_INCREMENT,
  `desc_log` VARCHAR(200) NOT NULL,
  `data_log` DATE NOT NULL,
  `hora_log` TIME NOT NULL,
  PRIMARY KEY (`cod_log`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleOS`.`atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleOS`.`atendimentos` (
  `cod_atendimento` INT NOT NULL AUTO_INCREMENT,
  `data_cad_atendimento` DATE NOT NULL,
  `ordem_atendimento` INT NOT NULL,
  `nota_atendimento` VARCHAR(10) NOT NULL,
  `os_resolve_atendimento` VARCHAR(3) NOT NULL,
  `obs_atendimento` TEXT NULL,
  PRIMARY KEY (`cod_atendimento`, `ordem_atendimento`),
  INDEX `cod_ordem_idx` (`ordem_atendimento` ASC),
  CONSTRAINT `cod_ordem`
    FOREIGN KEY (`ordem_atendimento`)
    REFERENCES `controleOS`.`ordens` (`cod_ondem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
